### ISSUE TITLE
It isnt working and I got an error help pls

### ISSUE THREAD

**Issue by gigawasian** [codyd51/offkeyboard#3]
I am trying to run it on windows in the PyCharm IDE.  When I try to run it, after already having installed pyaudio, I get this error:

Traceback (most recent call last):
  File "D:/Program Files/offkeyboard/offkeyboard/__init__.py", line 16, in <module>
    from note_reader import NoteReader
  File "D:\Program Files\offkeyboard\offkeyboard\note_reader.py", line 6, in <module>
    from keymaps import MarioMap
  File "D:\Program Files\offkeyboard\offkeyboard\keymaps.py", line 35, in <module>
    from mouse import MOUSE_UP_KEY, MOUSE_DOWN_KEY, MOUSE_LEFT_KEY, MOUSE_RIGHT_KEY, MOUSE_CLICK_KEY
  File "D:\Program Files\offkeyboard\offkeyboard\mouse.py", line 4, in <module>
    from Quartz.CoreGraphics import CGEventCreateMouseEvent
ModuleNotFoundError: No module named 'Quartz'

**Comment by gigawasian** [comment]
pls put a standalone in releases

**Comment by luiscarlos2000** [comment]
For me it's different, no window appears when I execute the setup.py on Windows. Will I get additional software?

**Comment by gigawasian** [comment]
when I run it (through python) this error screen appears and then it closes immediately after

**Comment by luiscarlos2000** [comment]
That's what I was traying to say sir! It seams that I maybe gonna do some changes to the code, but since I'm too basic for python it's kind of impossible.

**Comment by dayoshiguy** [comment]
rip :(

**Comment by SrYoel** [comment]
Same error on me... Please, someone help us!

**Comment by SrYoel** [comment]
ok Nobody is going to help us. I've been trying to fix this for 13 whole hours... NOTHING HAS CHANGED and the bad thing about this is that there is nobody in the world that can give us a hand and help us.

**Comment by gigawasian** [comment]
@codyd51

**Comment by Amature123** [comment]
How about Pyinstaller ?
Does is work?

**Comment by luiscarlos2000** [comment]
I really don't know if it works, but for me it didn't.

**Comment by gigawasian** [comment]
pyinstaller does not fix it
